# # Galaxy role dependencies

# - name: geerlingguy.docker
#   version: 3.0.0
# - name: geerlingguy.pip
#   version: 1.5.0
# - name: geerlingguy.nodejs
#   version: 3.0.0

# You don’t need to add become: yes in the task   no need to giev in sansible file