#SPDX-License-Identifier: MIT-0
---
# vars file for roles/common  lookyp act like for loops 
docker_registry_url:  "{{ lookup('env', 'DOCKER_REGISTRY_URL') }}"
docker_registry_username: "{{ lookup('env','DOCKER_USER') }}"
docker_registry_password: "{{ lookup('env','DOCKER_PASS') }}"
# app_image: "myregistry.com/automation-service:{{ TEST_ENV }}"
app_image: "{{ lookup('env', 'APP_IMAGE') }}"
