#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: yashwanth gowda
  description: installs kubectl and helm, creates namespace, deploys app to k8s
  license: GPL-2.0-or-later
  min_ansible_version: 2.2
