name: terraform
on:
   push:
    branches: [ "QA_main"]

env:
  AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION:            ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:

      # step 1 — checkout your code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}

      - name: Debuging
        run: |
          pwd
          ls -R
          

      # step 2 — install terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # step 3 — terraform init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # step 4 — check formatting
      - name: Terraform Format
        working-directory: terraform
        run: terraform fmt

      # step 5 — validate code
      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      # step 6 — plan (shows what will be created)
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var-file="terraform.tfvars"

      # step 7 — apply (only on push to main)
      - name: Terraform Apply
        working-directory: terraform
        if: (github.ref == 'refs/heads/Qa_main' ||  github.ref == 'refs/heads/main')  && github.event_name == 'push'
      #  insted >> overwrite     ,  > replace the values 
        run: |
      
          echo 'key_pairs = "${{ secrets.AWS_KEY_PAIR }}"' >> terraform.tfvars
          terraform apply -auto-approve -var-file="terraform.tfvars"
          


    # Save the Terraform state file as an artifact
      - name: Collect Terraform Outputs
        if: success()
        working-directory: terraform
        run: |
          echo "Saving Terraform outputs to project folder..."
          terraform output -json > ../terraform_outputs.json    


      # - name: Destroy on Failure
      #   if: success()
      #   working-directory: terraform
      #   run: terraform destroy -auto-approve